server:
  port: 8080

  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://47.93.136.4:3306/attendance
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5

  cache:
    type: redis
  redis:
    database: 0
    host: 47.93.136.4
    port: 6379
    password: 123456

    jedis:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 300
        min-idle: 0
    timeout: 10000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0